SELECT M.TITLE, M.RELYEAR,M.RATINGCODE, R.LONGDESC, C.COLOURNAME
FROM MOVIE1272 M
INNER JOIN RATING1272 R
ON M.RATINGCODE = R.RATINGCODE
INNER JOIN COLOURTYPE1272 C  
ON M.COLOURCODE = C.COLOURCODE
WHERE M.RUNTIME < 90
ORDER BY M.MOVIENO ASC;
