SELECT M.MOVIENO, M.TITLE,M.RATINGCODE, R.SHORTDESC, M.TMDB_SCORE
FROM MOVIE1272 M
INNER JOIN RATING1272 R
ON M.RATINGCODE = R.RATINGCODE
WHERE (M.RATINGCODE = 'MA' AND (RUNTIME >=100 AND <= 102)) 
OR  (M.RATINGCODE = 'G' AND RUNTIME < 90)
OR (M.RATINGCODE = 'MA' AND (RUNTIME >=120 AND <= 125)) 
OR (M.RATINGCODE = 'M' AND RUNTIME >= 180)
AND TMDB_SCORE >= 6.5 AND <= 7.5 
ORDER BY M.MOVIENO ASC;
