SELECT M.MOVIENO, M.TITLE, M.RUNTIME, M.TMDB_SCORE, R.LONGDESC
FROM MOVIE1272 M
INNER JOIN RATING1272 R
ON M.RATINGCODE = R.RATINGCODE
WHERE UPPER(R.LONGDESC) LIKE ('%RECOMMENDED%') OR LOWER(R.LONGDESC) LIKE ('%recommended%')
OR (M.TMDB_ID LIKE '%44%')
OR LOWER(M.TITLE) LIKE '%t%' OR UPPER(M.TITLE) LIKE ('%T%');



